services:
  postgresdb:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DB
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres


volumes:
  db: