spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  config:
    import: optional:file:.env[.properties]
  application:
    name: workfromhere-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${POSTGRESDB_USER}
    password: ${POSTGRESDB_PASSWORD}
    url: jdbc:postgresql://localhost:${POSTGRESDB_LOCAL_PORT}/${POSTGRESDB_DB}